apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpool-user
rules:
  - apiGroups:
      - 'hive.openshift.io'
    resources:
      - clusterclaims
    verbs:
      - get
      - watch
      - list
      - create
      - delete
  - apiGroups:
      - '' 
    resources:
      - secret
    verbs:
      - get
      - watch
      - list
      - create
      - delete
  - apiGroups:
      - 'hive.openshift.io'
    resources:
      - clusterdeployments
      - clusterprovisions
      - clusterdeprovisions
      - clusterpools
      - clusterimagesets
    verbs:
      - get
      - watch
      - list
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cicd-clusterpool-sa
  namespace: cicd
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-clusterpool-sa-user
subjects:
  - kind: ServiceAccount
    namespace: cicd
    name: cicd-clusterpool-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterpool-user
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-clusterpool-sa-clusterpool-view
  namespace: cicd
subjects:
  - kind: ServiceAccount
    namespace: cicd
    name: cicd-clusterpool-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
